##################################
### split_train_test
##################################

split_train_test:
  # input file for the train_test_split.py script
  input_file: "processed_data.csv"

  # output files for the train_test_split.py script
  train_output_file: "train_data.csv"
  test_output_file: "test_data.csv"

  # target column
  target_column: "target"

  # test size
  test_size: 0.2

  # random state
  random_state: 42

  # stratify
  stratify: False